/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrew
 */
import Old.TestSpace;
import java.sql.*;
import java.util.LinkedList;
import javax.swing.JTextArea;

public class TestSpaceDuplicate extends javax.swing.JFrame
{

    public DbInterface personDB = new DbInterface();
    private String currentScreen = "Main";

    /**
     * Creates new form NewJFrame
     */
    public TestSpaceDuplicate()
    {
        initComponents();
        guiSetup();
    }
    
    public void guiSetup()
    {
        refreshLists();
        joinPanel.setVisible(false);
        searchPanel.setVisible(false);
        adminPanel.setVisible(false);
    }
    
    public void invisAll()
    {
        startPanel.setVisible(false);
        searchPanel.setVisible(false);
        joinPanel.setVisible(false);
        adminPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPaneSearch = new javax.swing.JLayeredPane();
        startPanel = new javax.swing.JPanel();
        switchSearchButton1 = new javax.swing.JButton();
        switchJoinButton1 = new javax.swing.JButton();
        adminPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        AddUser = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lastNameField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        firstNameField = new javax.swing.JTextField();
        DOBfield = new javax.swing.JTextField();
        RemoveUser = new javax.swing.JButton();
        DOB = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listArea = new javax.swing.JTextArea();
        addressField = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        listPeopleButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        FirstNameText = new javax.swing.JLabel();
        clearButton = new javax.swing.JButton();
        LastNameText = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        joinPanel = new javax.swing.JPanel();
        joinLastNameField = new javax.swing.JTextField();
        joinFirstNameField = new javax.swing.JTextField();
        joinDOBfield = new javax.swing.JTextField();
        DOB2 = new javax.swing.JLabel();
        joinAddressField = new javax.swing.JTextField();
        Address2 = new javax.swing.JLabel();
        FirstNameText2 = new javax.swing.JLabel();
        joinButton = new javax.swing.JButton();
        LastNameText2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        searchLastNameField = new javax.swing.JTextField();
        searchFirstNameField = new javax.swing.JTextField();
        searchDOBfield = new javax.swing.JTextField();
        DOB1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchListArea = new javax.swing.JTextArea();
        searchAddressField = new javax.swing.JTextField();
        Address1 = new javax.swing.JLabel();
        searchRefresh = new javax.swing.JButton();
        searchAreaButton = new javax.swing.JButton();
        FirstNameText1 = new javax.swing.JLabel();
        SearchClearButton = new javax.swing.JButton();
        LastNameText1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        switchSearchButton = new javax.swing.JButton();
        mainButton = new javax.swing.JButton();
        switchJoinButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        layeredPaneSearch.setBackground(new java.awt.Color(0, 0, 204));
        layeredPaneSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        layeredPaneSearch.setAlignmentX(0.0F);
        layeredPaneSearch.setAlignmentY(0.0F);
        layeredPaneSearch.setEnabled(false);
        layeredPaneSearch.setPreferredSize(new java.awt.Dimension(600, 300));
        layeredPaneSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                layeredPaneSearchKeyPressed(evt);
            }
        });

        startPanel.setBackground(new java.awt.Color(185, 221, 239));
        startPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        startPanel.setForeground(new java.awt.Color(185, 221, 239));

        switchSearchButton1.setBackground(new java.awt.Color(255, 255, 255));
        switchSearchButton1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        switchSearchButton1.setForeground(new java.awt.Color(255, 255, 255));
        switchSearchButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Austin J. Baggio\\Pictures\\P3Images\\CloudButton.png")); // NOI18N
        switchSearchButton1.setText("Search");
        switchSearchButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        switchSearchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchSearchButton1ActionPerformed(evt);
            }
        });

        switchJoinButton1.setBackground(new java.awt.Color(255, 255, 255));
        switchJoinButton1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        switchJoinButton1.setForeground(new java.awt.Color(255, 255, 255));
        switchJoinButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Austin J. Baggio\\Pictures\\P3Images\\CloudButton.png")); // NOI18N
        switchJoinButton1.setText("Join");
        switchJoinButton1.setBorder(switchJoinButton1.getBorder());
        switchJoinButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        switchJoinButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchJoinButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addComponent(switchJoinButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(switchSearchButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(switchJoinButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(switchSearchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        adminPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        adminPanel.setPreferredSize(new java.awt.Dimension(580, 270));

        jButton1.setText("Français");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        AddUser.setText("Add Person");
        AddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserActionPerformed(evt);
            }
        });

        jButton2.setText("English");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });

        jButton3.setText("español");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        DOBfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBfieldActionPerformed(evt);
            }
        });

        RemoveUser.setText("Remove ID:");
        RemoveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveUserActionPerformed(evt);
            }
        });

        DOB.setText("Date of birth");

        listArea.setEditable(false);
        listArea.setColumns(20);
        listArea.setRows(5);
        jScrollPane1.setViewportView(listArea);

        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });

        Address.setText("Address");

        listPeopleButton.setText("Reset");
        listPeopleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listPeopleButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        FirstNameText.setText("First Name");

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        LastNameText.setText("Last Name");

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(FirstNameText)
                        .addGap(55, 55, 55)
                        .addComponent(LastNameText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addContainerGap(48, Short.MAX_VALUE)
                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DOB)
                    .addComponent(DOBfield, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Address)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton))))
            .addGroup(adminPanelLayout.createSequentialGroup()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(adminPanelLayout.createSequentialGroup()
                                .addComponent(RemoveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(listPeopleButton)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DOB)
                        .addComponent(LastNameText)
                        .addComponent(Address))
                    .addComponent(FirstNameText, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(clearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPanelLayout.createSequentialGroup()
                        .addComponent(AddUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RemoveUser)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(listPeopleButton))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        joinPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        joinPanel.setPreferredSize(new java.awt.Dimension(580, 270));

        joinLastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinLastNameFieldActionPerformed(evt);
            }
        });

        joinFirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinFirstNameFieldActionPerformed(evt);
            }
        });

        joinDOBfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinDOBfieldActionPerformed(evt);
            }
        });

        DOB2.setText("Date of birth");

        joinAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinAddressFieldActionPerformed(evt);
            }
        });

        Address2.setText("Address");

        FirstNameText2.setText("First Name");

        joinButton.setText("Join");
        joinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinButtonActionPerformed(evt);
            }
        });

        LastNameText2.setText("Last Name");

        jLabel1.setText("YYYY-MM-DD");

        jButton4.setText("START MENU");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout joinPanelLayout = new javax.swing.GroupLayout(joinPanel);
        joinPanel.setLayout(joinPanelLayout);
        joinPanelLayout.setHorizontalGroup(
            joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(joinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(joinPanelLayout.createSequentialGroup()
                        .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(joinPanelLayout.createSequentialGroup()
                                .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNameText2)
                                    .addComponent(LastNameText2))
                                .addGap(28, 28, 28)
                                .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(joinFirstNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(joinLastNameField)))
                            .addGroup(joinPanelLayout.createSequentialGroup()
                                .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DOB2)
                                    .addComponent(Address2))
                                .addGap(18, 18, 18)
                                .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(joinPanelLayout.createSequentialGroup()
                                        .addComponent(joinAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel1)
                                        .addGap(0, 52, Short.MAX_VALUE))
                                    .addComponent(joinDOBfield))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                        .addComponent(jButton4)))
                .addContainerGap())
        );
        joinPanelLayout.setVerticalGroup(
            joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinPanelLayout.createSequentialGroup()
                .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(joinPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(joinFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstNameText2)))
                    .addGroup(joinPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)))
                .addGap(18, 18, 18)
                .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameText2)
                    .addComponent(joinLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOB2)
                    .addComponent(joinAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address2)
                    .addComponent(joinDOBfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(joinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        searchPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchPanel.setPreferredSize(new java.awt.Dimension(580, 270));

        searchLastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchLastNameFieldActionPerformed(evt);
            }
        });

        searchFirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFirstNameFieldActionPerformed(evt);
            }
        });

        searchDOBfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDOBfieldActionPerformed(evt);
            }
        });

        DOB1.setText("Date of birth");

        searchListArea.setEditable(false);
        searchListArea.setColumns(20);
        searchListArea.setRows(5);
        jScrollPane2.setViewportView(searchListArea);

        searchAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAddressFieldActionPerformed(evt);
            }
        });

        Address1.setText("Address");

        searchRefresh.setText("Reset");
        searchRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRefreshActionPerformed(evt);
            }
        });

        searchAreaButton.setText("Search");
        searchAreaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchAreaButtonActionPerformed(evt);
            }
        });

        FirstNameText1.setText("First Name");

        SearchClearButton.setText("Clear");
        SearchClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchClearButtonActionPerformed(evt);
            }
        });

        LastNameText1.setText("Last Name");

        jButton5.setText("START MENU");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(FirstNameText1)
                        .addGap(55, 55, 55)
                        .addComponent(LastNameText1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DOB1)
                    .addComponent(searchDOBfield, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(Address1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addComponent(searchAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchAreaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchClearButton)))
                .addContainerGap())
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchRefresh)
                .addGap(40, 40, 40))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DOB1)
                            .addComponent(LastNameText1)
                            .addComponent(Address1))
                        .addComponent(FirstNameText1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDOBfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchAreaButton)
                    .addComponent(SearchClearButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchRefresh)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layeredPaneSearchLayout = new javax.swing.GroupLayout(layeredPaneSearch);
        layeredPaneSearch.setLayout(layeredPaneSearchLayout);
        layeredPaneSearchLayout.setHorizontalGroup(
            layeredPaneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(joinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
            .addGroup(layeredPaneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
            .addGroup(layeredPaneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
            .addGroup(layeredPaneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(startPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layeredPaneSearchLayout.setVerticalGroup(
            layeredPaneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(joinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
            .addGroup(layeredPaneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(adminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
            .addGroup(layeredPaneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE))
            .addGroup(layeredPaneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layeredPaneSearch.setLayer(startPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPaneSearch.setLayer(adminPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPaneSearch.setLayer(joinPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPaneSearch.setLayer(searchPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        switchSearchButton.setText("Search");
        switchSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchSearchButtonActionPerformed(evt);
            }
        });

        mainButton.setText("Admin");
        mainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainButtonActionPerformed(evt);
            }
        });

        switchJoinButton.setText("Join");
        switchJoinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchJoinButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainButton)
                .addGap(88, 88, 88)
                .addComponent(switchSearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(switchJoinButton))
            .addComponent(layeredPaneSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(layeredPaneSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(switchSearchButton)
                    .addComponent(mainButton)
                    .addComponent(switchJoinButton)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lastNameFieldActionPerformed
    {//GEN-HEADEREND:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_firstNameFieldActionPerformed
    {//GEN-HEADEREND:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void AddUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_AddUserActionPerformed
    {//GEN-HEADEREND:event_AddUserActionPerformed
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();
        String bDay = DOBfield.getText();
        String address = addressField.getText();
        personDB.addPerson(firstName, lastName, bDay, address);
        refreshList(listArea);
    }//GEN-LAST:event_AddUserActionPerformed

    private void RemoveUserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_RemoveUserActionPerformed
    {//GEN-HEADEREND:event_RemoveUserActionPerformed
        String id;
        id = idField.getText();
        personDB.removePerson(id);
        refreshList(listArea);
    }//GEN-LAST:event_RemoveUserActionPerformed

    private void listPeopleButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_listPeopleButtonActionPerformed
    {//GEN-HEADEREND:event_listPeopleButtonActionPerformed
        refreshList(listArea);
        //HERE as test  System.out.println(personDB.getFromID("2015-02-11 10:40:08.054000","DOB"));
    }//GEN-LAST:event_listPeopleButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        updateLabels("french");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        updateLabels("english");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        updateLabels("spanish");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DOBfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBfieldActionPerformed

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchButtonActionPerformed
    {//GEN-HEADEREND:event_searchButtonActionPerformed
        String firstName = firstNameField.getText();
        String lastName = lastNameField.getText();
        String bDay = DOBfield.getText();
        String address = addressField.getText();
        LinkedList results = personDB.searchDB(firstName, lastName, bDay, address);
        listArea.setText("");
        String current;
        for (int x = 0; x < results.size(); x++) {
            current = listArea.getText();
            listArea.setText(current+results.get(x)+"\n");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clearButtonActionPerformed
    {//GEN-HEADEREND:event_clearButtonActionPerformed
        firstNameField.setText("");
        lastNameField.setText("");
        DOBfield.setText("");
        addressField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void switchSearchButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_switchSearchButtonActionPerformed
    {//GEN-HEADEREND:event_switchSearchButtonActionPerformed
        invisAll();
        searchPanel.setVisible(true);
        refreshList(searchListArea);
                
    }//GEN-LAST:event_switchSearchButtonActionPerformed

    private void searchLastNameFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchLastNameFieldActionPerformed
    {//GEN-HEADEREND:event_searchLastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchLastNameFieldActionPerformed

    private void searchFirstNameFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchFirstNameFieldActionPerformed
    {//GEN-HEADEREND:event_searchFirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFirstNameFieldActionPerformed

    private void searchDOBfieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchDOBfieldActionPerformed
    {//GEN-HEADEREND:event_searchDOBfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchDOBfieldActionPerformed

    private void searchAddressFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchAddressFieldActionPerformed
    {//GEN-HEADEREND:event_searchAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchAddressFieldActionPerformed

    private void searchRefreshActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchRefreshActionPerformed
    {//GEN-HEADEREND:event_searchRefreshActionPerformed
        refreshList(searchListArea);
    }//GEN-LAST:event_searchRefreshActionPerformed

    private void searchAreaButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchAreaButtonActionPerformed
    {//GEN-HEADEREND:event_searchAreaButtonActionPerformed
        String firstName = searchFirstNameField.getText();
        String lastName = searchLastNameField.getText();
        String DOB = searchDOBfield.getText();
        String address = searchAddressField.getText();
        LinkedList results = personDB.searchDB(firstName, lastName, DOB, address);
        searchListArea.setText("");
        String current;
        for (int x = 0; x < results.size(); x++) {
            current = searchListArea.getText();
            searchListArea.setText(current+results.get(x)+"\n");
        }
    }//GEN-LAST:event_searchAreaButtonActionPerformed

    private void SearchClearButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SearchClearButtonActionPerformed
    {//GEN-HEADEREND:event_SearchClearButtonActionPerformed
        searchFirstNameField.setText("");
        searchLastNameField.setText("");
        searchDOBfield.setText("");
        searchAddressField.setText("");
    }//GEN-LAST:event_SearchClearButtonActionPerformed

    private void layeredPaneSearchKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_layeredPaneSearchKeyPressed
    {//GEN-HEADEREND:event_layeredPaneSearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_layeredPaneSearchKeyPressed

    private void mainButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mainButtonActionPerformed
    {//GEN-HEADEREND:event_mainButtonActionPerformed
        invisAll();
        adminPanel.setVisible(true);
        refreshList(listArea);
    }//GEN-LAST:event_mainButtonActionPerformed

    private void switchJoinButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_switchJoinButtonActionPerformed
    {//GEN-HEADEREND:event_switchJoinButtonActionPerformed
        invisAll();
        joinPanel.setVisible(true);
    }//GEN-LAST:event_switchJoinButtonActionPerformed

    private void joinLastNameFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_joinLastNameFieldActionPerformed
    {//GEN-HEADEREND:event_joinLastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinLastNameFieldActionPerformed

    private void joinFirstNameFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_joinFirstNameFieldActionPerformed
    {//GEN-HEADEREND:event_joinFirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinFirstNameFieldActionPerformed

    private void joinDOBfieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_joinDOBfieldActionPerformed
    {//GEN-HEADEREND:event_joinDOBfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinDOBfieldActionPerformed

    private void joinAddressFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_joinAddressFieldActionPerformed
    {//GEN-HEADEREND:event_joinAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinAddressFieldActionPerformed

    private void joinButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_joinButtonActionPerformed
    {//GEN-HEADEREND:event_joinButtonActionPerformed
        String firstName = joinFirstNameField.getText();
        String lastName = joinLastNameField.getText();
        String bDay = joinDOBfield.getText();
        String address = joinAddressField.getText();
        personDB.addPerson(firstName, lastName, bDay, address);
        invisAll();
        startPanel.setVisible(true);
        refreshLists();
    }//GEN-LAST:event_joinButtonActionPerformed

    private void switchSearchButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_switchSearchButton1ActionPerformed
    {//GEN-HEADEREND:event_switchSearchButton1ActionPerformed
        invisAll();
        searchPanel.setVisible(true);
    }//GEN-LAST:event_switchSearchButton1ActionPerformed

    private void switchJoinButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_switchJoinButton1ActionPerformed
    {//GEN-HEADEREND:event_switchJoinButton1ActionPerformed
        invisAll();
        joinPanel.setVisible(true);
    }//GEN-LAST:event_switchJoinButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        invisAll();
        startPanel.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton5ActionPerformed
    {//GEN-HEADEREND:event_jButton5ActionPerformed
        invisAll();
        startPanel.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void refreshLists()
    {
        refreshList(listArea);
        refreshList(searchListArea);
    }
    private void refreshList(JTextArea listToRefresh)
    {
        listToRefresh.setText("");
        String[] list = personDB.getList("firstname", "ASC");
        String current;
        int x = 0;
        while (list[x] != null) {
            current = listToRefresh.getText();
            listToRefresh.setText(current + list[x] + "\n");
            x++;
        }
    }

    private void updateLabels(String language)
    {
        FirstNameText.setText(personDB.getTitle("FirstName", language));
        LastNameText.setText(personDB.getTitle("LastName", language));
        AddUser.setText(personDB.getTitle("Add", language));
        RemoveUser.setText(personDB.getTitle("Remove", language));
        DOB.setText(personDB.getTitle("DOB", language));
        Address.setText(personDB.getTitle("Address", language));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new TestSpaceDuplicate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddUser;
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Address1;
    private javax.swing.JLabel Address2;
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel DOB1;
    private javax.swing.JLabel DOB2;
    private javax.swing.JTextField DOBfield;
    private javax.swing.JLabel FirstNameText;
    private javax.swing.JLabel FirstNameText1;
    private javax.swing.JLabel FirstNameText2;
    private javax.swing.JLabel LastNameText;
    private javax.swing.JLabel LastNameText1;
    private javax.swing.JLabel LastNameText2;
    private javax.swing.JButton RemoveUser;
    private javax.swing.JButton SearchClearButton;
    private javax.swing.JTextField addressField;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField joinAddressField;
    private javax.swing.JButton joinButton;
    private javax.swing.JTextField joinDOBfield;
    private javax.swing.JTextField joinFirstNameField;
    private javax.swing.JTextField joinLastNameField;
    private javax.swing.JPanel joinPanel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLayeredPane layeredPaneSearch;
    private javax.swing.JTextArea listArea;
    private javax.swing.JButton listPeopleButton;
    private javax.swing.JButton mainButton;
    private javax.swing.JTextField searchAddressField;
    private javax.swing.JButton searchAreaButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchDOBfield;
    private javax.swing.JTextField searchFirstNameField;
    private javax.swing.JTextField searchLastNameField;
    private javax.swing.JTextArea searchListArea;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JButton searchRefresh;
    private javax.swing.JPanel startPanel;
    private javax.swing.JButton switchJoinButton;
    private javax.swing.JButton switchJoinButton1;
    private javax.swing.JButton switchSearchButton;
    private javax.swing.JButton switchSearchButton1;
    // End of variables declaration//GEN-END:variables
}
