/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrew
 */
import java.sql.*;
import java.util.LinkedList;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

public class TestSpaceDuplicate extends javax.swing.JFrame
{

    public DbInterface personDB = new DbInterface();
    private String currentScreen = "Main";
    public String stationID = "0";
    private String[] firstNameLang = {"First Name", "Prénom", "Nombre"};
    private String[] lastNameLang = {"Last Name", "Nom de Famille", "Apellido"};
    private String[] addLang = {"Add User", "Ajouté", "Añadir persona"};
    private String[] DOBLang = {"Date of birth", "Date de naissance", "Fecha de nacimiento"};
    private String[] removeLang = {"Remove User", "Suprimé", "Eliminar"};
    private String[] addressLang = {"Address", "Addresse", "Direcciòn"};
    private String[] searchLang = {"Search", "recherche", "Búsqueda"};
    private String[] helpLang = {"Request Help", "Aide Requis", "Ayuda"};
    private String[] joinLang = {"Join", "Ajoutez", "Joindre"};
    private String[] clearLang = {"Clear", "Remettre", "Reajustar"};
    private String[] refreshLang = {"Refresh", "rafraîchir", "Refrescar"};
    private String[] startMenuLang = {"Main Menu", "menu", "menú"};

    /**
     * Creates new form NewJFrame
     */
    public TestSpaceDuplicate()
    {
        initComponents();
        guiSetup();
    }

    /**
     *
     */
    public void guiSetup()
    {
        refreshLists();
        stationID = Integer.toString((int) (Math.random() * 10000.0));
        stationIdLabel.setText(stationID);
        joinPanel.setVisible(false);
        searchPanel.setVisible(false);
    }

    /**
     *
     */
    public void invisAll()
    {
        startPanel.setVisible(false);
        searchPanel.setVisible(false);
        joinPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        layeredPaneSearch = new javax.swing.JLayeredPane();
        startPanel = new javax.swing.JPanel();
        switchSearchButton1 = new javax.swing.JButton();
        switchJoinButton1 = new javax.swing.JButton();
        joinPanel = new javax.swing.JPanel();
        joinLastNameField = new javax.swing.JTextField();
        joinFirstNameField = new javax.swing.JTextField();
        joinAddressField = new javax.swing.JTextField();
        DOB2 = new javax.swing.JLabel();
        joinDOBfield = new javax.swing.JTextField();
        Address2 = new javax.swing.JLabel();
        FirstNameText2 = new javax.swing.JLabel();
        joinButton = new javax.swing.JButton();
        LastNameText2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        startMenuButton = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        searchLastNameField = new javax.swing.JTextField();
        searchFirstNameField = new javax.swing.JTextField();
        searchDOBfield = new javax.swing.JTextField();
        DOB1 = new javax.swing.JLabel();
        searchAddressField = new javax.swing.JTextField();
        Address1 = new javax.swing.JLabel();
        searchRefresh = new javax.swing.JButton();
        searchAreaButton = new javax.swing.JButton();
        FirstNameText1 = new javax.swing.JLabel();
        SearchClearButton = new javax.swing.JButton();
        LastNameText1 = new javax.swing.JLabel();
        searchStartMenuButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        searchTable = new javax.swing.JTable();
        helpButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        stationIdLabel = new javax.swing.JTextField();
        lockInButton = new javax.swing.JButton();
        englishButton = new javax.swing.JButton();
        frenchButton = new javax.swing.JButton();
        spanishbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(206, 229, 240));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(206, 229, 240));
        setLocationByPlatform(true);
        setResizable(false);

        layeredPaneSearch.setBackground(new java.awt.Color(206, 229, 240));
        layeredPaneSearch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        layeredPaneSearch.setForeground(new java.awt.Color(206, 229, 240));
        layeredPaneSearch.setToolTipText("");
        layeredPaneSearch.setAlignmentX(0.0F);
        layeredPaneSearch.setAlignmentY(0.0F);
        layeredPaneSearch.setEnabled(false);
        layeredPaneSearch.setPreferredSize(new java.awt.Dimension(600, 500));
        layeredPaneSearch.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                layeredPaneSearchKeyPressed(evt);
            }
        });

        startPanel.setBackground(new java.awt.Color(206, 229, 240));
        startPanel.setForeground(new java.awt.Color(255, 255, 255));

        switchSearchButton1.setBackground(new java.awt.Color(255, 255, 255));
        switchSearchButton1.setFont(new java.awt.Font("Tahoma", 0, 120)); // NOI18N
        switchSearchButton1.setForeground(new java.awt.Color(255, 255, 255));
        switchSearchButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/ButtonBlue.png"))); // NOI18N
        switchSearchButton1.setText("Search");
        switchSearchButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        switchSearchButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                switchSearchButton1ActionPerformed(evt);
            }
        });

        switchJoinButton1.setBackground(new java.awt.Color(255, 255, 255));
        switchJoinButton1.setFont(new java.awt.Font("Tahoma", 0, 140)); // NOI18N
        switchJoinButton1.setForeground(new java.awt.Color(255, 255, 255));
        switchJoinButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/ButtonBlue.png"))); // NOI18N
        switchJoinButton1.setText("Join");
        switchJoinButton1.setBorder(switchJoinButton1.getBorder());
        switchJoinButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        switchJoinButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                switchJoinButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(switchJoinButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(switchSearchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(switchJoinButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(switchSearchButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        joinPanel.setBackground(new java.awt.Color(206, 232, 232));
        joinPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        joinPanel.setPreferredSize(new java.awt.Dimension(580, 660));

        joinLastNameField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        joinLastNameField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                joinLastNameFieldActionPerformed(evt);
            }
        });

        joinFirstNameField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        joinFirstNameField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                joinFirstNameFieldActionPerformed(evt);
            }
        });

        joinAddressField.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        joinAddressField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                joinAddressFieldActionPerformed(evt);
            }
        });

        DOB2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        DOB2.setText("Date of birth");

        joinDOBfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        joinDOBfield.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                joinDOBfieldActionPerformed(evt);
            }
        });

        Address2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        Address2.setText("Address");

        FirstNameText2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        FirstNameText2.setText("First Name");

        joinButton.setBackground(new java.awt.Color(222, 232, 252));
        joinButton.setFont(new java.awt.Font("Tahoma", 0, 150)); // NOI18N
        joinButton.setForeground(new java.awt.Color(255, 255, 255));
        joinButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/ButtonBlue.png"))); // NOI18N
        joinButton.setText("Join");
        joinButton.setBorder(null);
        joinButton.setBorderPainted(false);
        joinButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        joinButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                joinButtonActionPerformed(evt);
            }
        });

        LastNameText2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        LastNameText2.setText("Last Name");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("YYYY-MM-DD");

        startMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        startMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/SmallCopyButton.PNG"))); // NOI18N
        startMenuButton.setText("Start Menu");
        startMenuButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startMenuButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                startMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout joinPanelLayout = new javax.swing.GroupLayout(joinPanel);
        joinPanel.setLayout(joinPanelLayout);
        joinPanelLayout.setHorizontalGroup(
            joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(joinPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinPanelLayout.createSequentialGroup()
                        .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(joinDOBfield, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(joinFirstNameField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DOB2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(joinLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(FirstNameText2))
                        .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(joinPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(startMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))))
                    .addGroup(joinPanelLayout.createSequentialGroup()
                        .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Address2)
                            .addComponent(LastNameText2)
                            .addComponent(joinAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(joinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(joinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );
        joinPanelLayout.setVerticalGroup(
            joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, joinPanelLayout.createSequentialGroup()
                .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(joinPanelLayout.createSequentialGroup()
                        .addComponent(FirstNameText2)
                        .addGap(4, 4, 4)
                        .addComponent(joinFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(startMenuButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LastNameText2)
                .addGap(5, 5, 5)
                .addComponent(joinLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DOB2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(joinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joinDOBfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(1, 1, 1)
                .addComponent(Address2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joinAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        searchPanel.setBackground(new java.awt.Color(255, 210, 161));
        searchPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchPanel.setForeground(new java.awt.Color(206, 229, 240));
        searchPanel.setPreferredSize(new java.awt.Dimension(580, 660));

        searchLastNameField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        searchLastNameField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                searchLastNameFieldActionPerformed(evt);
            }
        });

        searchFirstNameField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        searchFirstNameField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                searchFirstNameFieldActionPerformed(evt);
            }
        });

        searchDOBfield.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        searchDOBfield.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                searchDOBfieldActionPerformed(evt);
            }
        });

        DOB1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        DOB1.setText("Date of birth");

        searchAddressField.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        searchAddressField.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                searchAddressFieldActionPerformed(evt);
            }
        });

        Address1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Address1.setText("Address");

        searchRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/SmallCopyButtonGreen.png"))); // NOI18N
        searchRefresh.setText("Refresh");
        searchRefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchRefresh.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                searchRefreshActionPerformed(evt);
            }
        });

        searchAreaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/SmallCopyButtonGreen.png"))); // NOI18N
        searchAreaButton.setText("Search");
        searchAreaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchAreaButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                searchAreaButtonActionPerformed(evt);
            }
        });

        FirstNameText1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        FirstNameText1.setText("First Name");

        SearchClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/SmallCopyButtonGreen.png"))); // NOI18N
        SearchClearButton.setText("Clear");
        SearchClearButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SearchClearButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SearchClearButtonActionPerformed(evt);
            }
        });

        LastNameText1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        LastNameText1.setText("Last Name");

        searchStartMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/LongGreen.png"))); // NOI18N
        searchStartMenuButton.setText("START MENU");
        searchStartMenuButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchStartMenuButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                searchStartMenuButtonActionPerformed(evt);
            }
        });

        searchTable.setAutoCreateRowSorter(true);
        searchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "First Name", "Last Name", "Date Of Birth", "Address"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(searchTable);

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE))
                    .addGroup(searchPanelLayout.createSequentialGroup()
                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addComponent(searchStartMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(searchPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FirstNameText1)
                                    .addComponent(LastNameText1)
                                    .addComponent(searchFirstNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                    .addComponent(searchLastNameField))
                                .addGap(44, 44, 44)
                                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(searchPanelLayout.createSequentialGroup()
                                        .addComponent(SearchClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(searchRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(searchAddressField)
                                    .addGroup(searchPanelLayout.createSequentialGroup()
                                        .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(DOB1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Address1)
                                            .addComponent(searchDOBfield))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(53, 53, 53)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(searchAreaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameText1)
                    .addComponent(DOB1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchFirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDOBfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameText1)
                    .addComponent(Address1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchAreaButton)
                    .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SearchClearButton)
                        .addComponent(searchRefresh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchStartMenuButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layeredPaneSearchLayout = new javax.swing.GroupLayout(layeredPaneSearch);
        layeredPaneSearch.setLayout(layeredPaneSearchLayout);
        layeredPaneSearchLayout.setHorizontalGroup(
            layeredPaneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(joinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
            .addGroup(layeredPaneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
            .addGroup(layeredPaneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(startPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layeredPaneSearchLayout.setVerticalGroup(
            layeredPaneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(joinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
            .addGroup(layeredPaneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE))
            .addGroup(layeredPaneSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(startPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layeredPaneSearch.setLayer(startPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPaneSearch.setLayer(joinPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPaneSearch.setLayer(searchPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        helpButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        helpButton.setForeground(new java.awt.Color(255, 255, 255));
        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/ButtonBlue.png"))); // NOI18N
        helpButton.setText("Request Help");
        helpButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        helpButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                helpButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Station ID:");

        stationIdLabel.setText("0");

        lockInButton.setForeground(new java.awt.Color(255, 255, 255));
        lockInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/SmallCopyButton.PNG"))); // NOI18N
        lockInButton.setText("Lock In");
        lockInButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lockInButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                lockInButtonActionPerformed(evt);
            }
        });

        englishButton.setForeground(new java.awt.Color(255, 255, 255));
        englishButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/SmallCopyButton.PNG"))); // NOI18N
        englishButton.setText("English");
        englishButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        englishButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                englishButtonActionPerformed(evt);
            }
        });

        frenchButton.setForeground(new java.awt.Color(255, 255, 255));
        frenchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/SmallCopyButton.PNG"))); // NOI18N
        frenchButton.setText("Francais");
        frenchButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        frenchButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                frenchButtonActionPerformed(evt);
            }
        });

        spanishbutton.setForeground(new java.awt.Color(255, 255, 255));
        spanishbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics/SmallCopyButton.PNG"))); // NOI18N
        spanishbutton.setText("Spanish");
        spanishbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        spanishbutton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                spanishbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(layeredPaneSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(spanishbutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(frenchButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(englishButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lockInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(stationIdLabel))
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(stationIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lockInButton)
                        .addGap(110, 110, 110)
                        .addComponent(englishButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(frenchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spanishbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(layeredPaneSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchLastNameFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchLastNameFieldActionPerformed
    {//GEN-HEADEREND:event_searchLastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchLastNameFieldActionPerformed

    private void searchFirstNameFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchFirstNameFieldActionPerformed
    {//GEN-HEADEREND:event_searchFirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFirstNameFieldActionPerformed

    private void searchDOBfieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchDOBfieldActionPerformed
    {//GEN-HEADEREND:event_searchDOBfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchDOBfieldActionPerformed

    private void searchAddressFieldActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchAddressFieldActionPerformed
    {//GEN-HEADEREND:event_searchAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchAddressFieldActionPerformed

    private void searchRefreshActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchRefreshActionPerformed
    {//GEN-HEADEREND:event_searchRefreshActionPerformed

        refreshList(searchTable);
    }//GEN-LAST:event_searchRefreshActionPerformed

    private void searchAreaButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchAreaButtonActionPerformed
    {//GEN-HEADEREND:event_searchAreaButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) searchTable.getModel();
        Person tempPerson;
        String firstName = searchFirstNameField.getText();
        String lastName = searchLastNameField.getText();
        String DOB = searchDOBfield.getText();
        String address = searchAddressField.getText();
        LinkedList results = personDB.searchDB(firstName, lastName, DOB, address);
        int rows = model.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        String current;
        for (int x = 0; x < results.size(); x++) {
            tempPerson = (Person) results.get(x);
            model.addRow(new Object[]{tempPerson.getFirstName(), tempPerson.getLastName(), tempPerson.getDOB(), tempPerson.getAddress()});
        }
    }//GEN-LAST:event_searchAreaButtonActionPerformed

    private void SearchClearButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SearchClearButtonActionPerformed
    {//GEN-HEADEREND:event_SearchClearButtonActionPerformed
        searchFirstNameField.setText("");
        searchLastNameField.setText("");
        searchDOBfield.setText("");
        searchAddressField.setText("");
    }//GEN-LAST:event_SearchClearButtonActionPerformed

    private void layeredPaneSearchKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_layeredPaneSearchKeyPressed
    {//GEN-HEADEREND:event_layeredPaneSearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_layeredPaneSearchKeyPressed

    private void switchSearchButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_switchSearchButton1ActionPerformed
    {//GEN-HEADEREND:event_switchSearchButton1ActionPerformed
        invisAll();
        searchPanel.setVisible(true);
        searchFirstNameField.setText("");
        searchLastNameField.setText("");
        searchAddressField.setText("");
        searchDOBfield.setText("");
        refreshLists();
    }//GEN-LAST:event_switchSearchButton1ActionPerformed

    private void switchJoinButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_switchJoinButton1ActionPerformed
    {//GEN-HEADEREND:event_switchJoinButton1ActionPerformed
        invisAll();
        joinPanel.setVisible(true);
        joinFirstNameField.setText("");
        joinLastNameField.setText("");
        joinDOBfield.setText("");
        joinAddressField.setText("");
    }//GEN-LAST:event_switchJoinButton1ActionPerformed

    private void searchStartMenuButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_searchStartMenuButtonActionPerformed
    {//GEN-HEADEREND:event_searchStartMenuButtonActionPerformed
        invisAll();
        startPanel.setVisible(true);
    }//GEN-LAST:event_searchStartMenuButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_helpButtonActionPerformed
    {//GEN-HEADEREND:event_helpButtonActionPerformed
        personDB.addStation(stationID);
    }//GEN-LAST:event_helpButtonActionPerformed

    private void lockInButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_lockInButtonActionPerformed
    {//GEN-HEADEREND:event_lockInButtonActionPerformed
        stationID = stationIdLabel.getText();
        stationIdLabel.setEditable(false);
        lockInButton.setVisible(false);
    }//GEN-LAST:event_lockInButtonActionPerformed

    private void spanishbuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_spanishbuttonActionPerformed
    {//GEN-HEADEREND:event_spanishbuttonActionPerformed
        updateLabels(2);
    }//GEN-LAST:event_spanishbuttonActionPerformed

    private void englishButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_englishButtonActionPerformed
    {//GEN-HEADEREND:event_englishButtonActionPerformed
        updateLabels(0);
    }//GEN-LAST:event_englishButtonActionPerformed

    private void frenchButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_frenchButtonActionPerformed
    {//GEN-HEADEREND:event_frenchButtonActionPerformed
        updateLabels(1);
    }//GEN-LAST:event_frenchButtonActionPerformed

    private void startMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startMenuButtonActionPerformed
        invisAll();
        startPanel.setVisible(true);
    }//GEN-LAST:event_startMenuButtonActionPerformed

    private void joinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinButtonActionPerformed
        String firstName = joinFirstNameField.getText();
        String lastName = joinLastNameField.getText();
        String bDay = joinDOBfield.getText();
        String address = joinAddressField.getText();
        personDB.addPerson(firstName, lastName, bDay, address);
        invisAll();
        startPanel.setVisible(true);
        refreshLists();
    }//GEN-LAST:event_joinButtonActionPerformed

    private void joinDOBfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinDOBfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinDOBfieldActionPerformed

    private void joinAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinAddressFieldActionPerformed

    private void joinFirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinFirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinFirstNameFieldActionPerformed

    private void joinLastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinLastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_joinLastNameFieldActionPerformed

    /**
     *
     */
    private void refreshLists()
    {
        refreshList(searchTable);
    }

    /**
     *
     * @param listToRefresh
     */
    private void refreshList(JTable tableToRefresh)
    {
        DefaultTableModel model = (DefaultTableModel) tableToRefresh.getModel();
        int rows = model.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        Person tempPerson;
        LinkedList list = personDB.getList();
        String current;
        //int x = 0;
        for (int x = 0; x < list.size(); x++) {
            tempPerson = (Person) list.get(x);
            model.addRow(new Object[]{tempPerson.getFirstName(), tempPerson.getLastName(), tempPerson.getDOB(), tempPerson.getAddress()});
        }
    }

    /**
     *
     * @param language
     */
    private void updateLabels(int language)
    {
        //Start Page
        switchJoinButton1.setText(joinLang[language]);
        switchSearchButton1.setText(searchLang[language]);
        helpButton.setText(helpLang[language]);

        //Join Page
        FirstNameText2.setText(firstNameLang[language]);
        LastNameText2.setText(lastNameLang[language]);
        DOB2.setText(DOBLang[language]);
        Address2.setText(addressLang[language]);
        joinButton.setText(joinLang[language]);
        startMenuButton.setText(startMenuLang[language]);

        //Search Page
        LastNameText1.setText(lastNameLang[language]);
        FirstNameText1.setText(firstNameLang[language]);
        DOB1.setText(DOBLang[language]);
        Address1.setText(addressLang[language]);
        searchAreaButton.setText(searchLang[language]);
        SearchClearButton.setText(clearLang[language]);
        searchRefresh.setText(refreshLang[language]);
        searchStartMenuButton.setText(startMenuLang[language]);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestSpace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new TestSpaceDuplicate().setVisible(true);
            }
        });
    }
    /*void ColourChange(){
     initComponents();
     getContentPane().setBackground(new Color(206,229,240));
     }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address1;
    private javax.swing.JLabel Address2;
    private javax.swing.JLabel DOB1;
    private javax.swing.JLabel DOB2;
    private javax.swing.JLabel FirstNameText1;
    private javax.swing.JLabel FirstNameText2;
    private javax.swing.JLabel LastNameText1;
    private javax.swing.JLabel LastNameText2;
    private javax.swing.JButton SearchClearButton;
    private javax.swing.JButton englishButton;
    private javax.swing.JButton frenchButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField joinAddressField;
    private javax.swing.JButton joinButton;
    private javax.swing.JTextField joinDOBfield;
    private javax.swing.JTextField joinFirstNameField;
    private javax.swing.JTextField joinLastNameField;
    private javax.swing.JPanel joinPanel;
    private javax.swing.JLayeredPane layeredPaneSearch;
    private javax.swing.JButton lockInButton;
    private javax.swing.JTextField searchAddressField;
    private javax.swing.JButton searchAreaButton;
    private javax.swing.JTextField searchDOBfield;
    private javax.swing.JTextField searchFirstNameField;
    private javax.swing.JTextField searchLastNameField;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JButton searchRefresh;
    private javax.swing.JButton searchStartMenuButton;
    private javax.swing.JTable searchTable;
    private javax.swing.JButton spanishbutton;
    private javax.swing.JButton startMenuButton;
    private javax.swing.JPanel startPanel;
    private javax.swing.JTextField stationIdLabel;
    private javax.swing.JButton switchJoinButton1;
    private javax.swing.JButton switchSearchButton1;
    // End of variables declaration//GEN-END:variables
}
